// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OTSchedule_Modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OTSchedule_Modified));
        
        string IMigrationMetadata.Id
        {
            get { return "201812081740194_OTSchedule_Modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
