// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Sept06_OPDPatien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sept06_OPDPatien));
        
        string IMigrationMetadata.Id
        {
            get { return "201809061441032_Sept06_OPDPatien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
