// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DiscountCardPrintView_Modified_2_Oct21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DiscountCardPrintView_Modified_2_Oct21));
        
        string IMigrationMetadata.Id
        {
            get { return "201810210706068_DiscountCardPrintView_Modified_2_Oct21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
