// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Sept11_apply_ll_fixing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sept11_apply_ll_fixing));
        
        string IMigrationMetadata.Id
        {
            get { return "201809111327367_Sept11_apply_ll_fixing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
