// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PathologyReport_Model_Mdofied : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PathologyReport_Model_Mdofied));
        
        string IMigrationMetadata.Id
        {
            get { return "201811220958080_PathologyReport_Model_Mdofied"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
