// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _26052018m12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_26052018m12));
        
        string IMigrationMetadata.Id
        {
            get { return "201805260920042_26052018m12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
