// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Sept23_Transactiontime_added_with_ledgers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sept23_Transactiontime_added_with_ledgers));
        
        string IMigrationMetadata.Id
        {
            get { return "201809221801289_Sept23_Transactiontime_added_with_ledgers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
