// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Member_Employee_Ledger_Fixing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Member_Employee_Ledger_Fixing));
        
        string IMigrationMetadata.Id
        {
            get { return "201809181251282_Member_Employee_Ledger_Fixing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
