// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OPD_ServiceCost_Updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OPD_ServiceCost_Updated));
        
        string IMigrationMetadata.Id
        {
            get { return "201809050704354_OPD_ServiceCost_Updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
