// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hp_opd_consultant_category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hp_opd_consultant_category));
        
        string IMigrationMetadata.Id
        {
            get { return "201809020741472_hp_opd_consultant_category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
