// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxMedicine_RxTest_Template_Model_Created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxMedicine_RxTest_Template_Model_Created));
        
        string IMigrationMetadata.Id
        {
            get { return "201903020657047_RxMedicine_RxTest_Template_Model_Created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
