// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Hr_Module_Added_And_Modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Hr_Module_Added_And_Modified));
        
        string IMigrationMetadata.Id
        {
            get { return "201901241127140_Hr_Module_Added_And_Modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
