// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LIS_ModuleAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LIS_ModuleAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201908031043051_LIS_Module-Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
