// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LIS_Module_Remove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LIS_Module_Remove));
        
        string IMigrationMetadata.Id
        {
            get { return "201908031045359_LIS_Module_Remove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
