// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TreatmentOnDischarge_Model_Modified_Sept_02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TreatmentOnDischarge_Model_Modified_Sept_02));
        
        string IMigrationMetadata.Id
        {
            get { return "201909011514239_TreatmentOnDischarge_Model_Modified_Sept_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
