// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OPDBills_Modesl_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OPDBills_Modesl_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201904180548364_OPDBills_Modesl_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
