// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Patient_Model_Modified_Oct14_2019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Patient_Model_Modified_Oct14_2019));
        
        string IMigrationMetadata.Id
        {
            get { return "201910140143095_Patient_Model_Modified_Oct14_2019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
