// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DischargeCertificateTemplateBased_model_modified_aug28 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DischargeCertificateTemplateBased_model_modified_aug28));
        
        string IMigrationMetadata.Id
        {
            get { return "201908281639005_DischargeCertificateTemplateBased_model_modified_aug28"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
