// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PhModel_Changes_Jun01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PhModel_Changes_Jun01));
        
        string IMigrationMetadata.Id
        {
            get { return "201906011047243_PhModel_Changes_Jun01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
