// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxPatient_Model_Modified_March_07 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxPatient_Model_Modified_March_07));
        
        string IMigrationMetadata.Id
        {
            get { return "201903070303402_RxPatient_Model_Modified_March_07"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
