// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BarCodeLabelSettingForTest_Model_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BarCodeLabelSettingForTest_Model_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201907161108596_BarCodeLabelSettingForTest_Model_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
