// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxPatientInfo_Model_Modified_May14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxPatientInfo_Model_Modified_May14));
        
        string IMigrationMetadata.Id
        {
            get { return "201905141108353_RxPatientInfo_Model_Modified_May14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
