// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PhReceive_Model_Modified_March23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PhReceive_Model_Modified_March23));
        
        string IMigrationMetadata.Id
        {
            get { return "201903230656274_PhReceive_Model_Modified_March23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
