// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MAH_Model_Modifed_May23_2019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MAH_Model_Modifed_May23_2019));
        
        string IMigrationMetadata.Id
        {
            get { return "201905231114235_MAH_Model_Modifed_May23_2019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
