// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class barcodelabelsettings_mofifed_july28 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(barcodelabelsettings_mofifed_july28));
        
        string IMigrationMetadata.Id
        {
            get { return "201907280407455_barcodelabelsettings_mofifed_july28"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
