// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChamberPractitiner_Model_Modified_Apr18_19 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChamberPractitiner_Model_Modified_Apr18_19));
        
        string IMigrationMetadata.Id
        {
            get { return "201904172207063_ChamberPractitiner_Model_Modified_Apr18_19"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
