// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Doctor_M_Modified_Feb03_12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Doctor_M_Modified_Feb03_12));
        
        string IMigrationMetadata.Id
        {
            get { return "201902040221067_Doctor_M_Modified_Feb03_12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
