// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HpMedicineReturnIndentDetail_ModelModified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HpMedicineReturnIndentDetail_ModelModified));
        
        string IMigrationMetadata.Id
        {
            get { return "201902020611136_HpMedicineReturnIndentDetail_Model-Modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
