// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RegDiscountPlan_Model_Modified_Dec26 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegDiscountPlan_Model_Modified_Dec26));
        
        string IMigrationMetadata.Id
        {
            get { return "201912260813580_RegDiscountPlan_Model_Modified_Dec26"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
