// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PhReturnToSupplier_Model_Modified_May23_02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PhReturnToSupplier_Model_Modified_May23_02));
        
        string IMigrationMetadata.Id
        {
            get { return "201905231554007_PhReturnToSupplier_Model_Modified_May23_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
