// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class unknwon_model_modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(unknwon_model_modified));
        
        string IMigrationMetadata.Id
        {
            get { return "201901010707166_unknwon_model_modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
