// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxDosage_Modified_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxDosage_Modified_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201901030441101_RxDosage_Modified_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
