// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HospitalPatientInfo_Moedel_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HospitalPatientInfo_Moedel_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201903260601571_HospitalPatientInfo_Moedel_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
