// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Jun02_2019_HpMedicineRequisitionDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jun02_2019_HpMedicineRequisitionDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201906020838087_Jun02_2019_HpMedicineRequisitionDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
