// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HospitalPatientInfo_Model_Modified_Aug01_2019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HospitalPatientInfo_Model_Modified_Aug01_2019));
        
        string IMigrationMetadata.Id
        {
            get { return "201908010438559_HospitalPatientInfo_Model_Modified_Aug01_2019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
