// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxPatient_model_modified_May21_02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxPatient_model_modified_May21_02));
        
        string IMigrationMetadata.Id
        {
            get { return "201905211534084_RxPatient_model_modified_May21_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
