// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Module_Model_Modified_Active_InActive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Module_Model_Modified_Active_InActive));
        
        string IMigrationMetadata.Id
        {
            get { return "201901241135226_Module_Model_Modified_Active_InActive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
