// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxDosage_Model_Modified_Jun05_2020_05 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxDosage_Model_Modified_Jun05_2020_05));
        
        string IMigrationMetadata.Id
        {
            get { return "202006051837214_RxDosage_Model_Modified_Jun05_2020_05"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
