// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxCpAdviceTemplateDetail_Model_Modified_May30_2020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxCpAdviceTemplateDetail_Model_Modified_May30_2020));
        
        string IMigrationMetadata.Id
        {
            get { return "202005301738243_RxCpAdviceTemplateDetail_Model_Modified_May30_2020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
