// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxAdviceToPatient_Model_Modified_Apr05 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxAdviceToPatient_Model_Modified_Apr05));
        
        string IMigrationMetadata.Id
        {
            get { return "202004051704427_RxAdviceToPatient_Model_Modified_Apr05"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
