// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Pathmachine_Temp_Lis_Model_Modified_Jan14_2020_10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pathmachine_Temp_Lis_Model_Modified_Jan14_2020_10));
        
        string IMigrationMetadata.Id
        {
            get { return "202001151430239_Pathmachine_Temp_Lis_Model_Modified_Jan14_2020_10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
