// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxPrescriprionPart_1_2_3_Model_Added_Apr05 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxPrescriprionPart_1_2_3_Model_Added_Apr05));
        
        string IMigrationMetadata.Id
        {
            get { return "202004052136135_RxPrescriprionPart_1_2_3_Model_Added_Apr05"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
