// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_Model_Modified_for_RxChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Model_Modified_for_RxChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202005042025082_User_Model_Modified_for_RxChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
