// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxChanges_On_March_03_2020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxChanges_On_March_03_2020));
        
        string IMigrationMetadata.Id
        {
            get { return "202004030856083_RxChanges_On_March_03_2020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
