// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HpPatientAccomodationType_Model_Modified_Feb03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HpPatientAccomodationType_Model_Modified_Feb03));
        
        string IMigrationMetadata.Id
        {
            get { return "202002041140268_HpPatientAccomodationType_Model_Modified_Feb03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
