// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxInitialData_Model_Modified_Feb24_2020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxInitialData_Model_Modified_Feb24_2020));
        
        string IMigrationMetadata.Id
        {
            get { return "202002240739516_RxInitialData_Model_Modified_Feb24_2020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
