// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxModel_Added_Modofied_Feb23_2020_02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxModel_Added_Modofied_Feb23_2020_02));
        
        string IMigrationMetadata.Id
        {
            get { return "202002231322166_RxModel_Added_Modofied_Feb23_2020_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
