// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FloorAndDeptMapping_Model_Added_Jan14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FloorAndDeptMapping_Model_Added_Jan14));
        
        string IMigrationMetadata.Id
        {
            get { return "202001140350103_FloorAndDeptMapping_Model_Added_Jan14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
