// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxCPPreferredMedicine_Model_Modified_Apr26_2020_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxCPPreferredMedicine_Model_Modified_Apr26_2020_01));
        
        string IMigrationMetadata.Id
        {
            get { return "202004261147302_RxCPPreferredMedicine_Model_Modified_Apr26_2020_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
