// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxModels_Added_Modified_Feb23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxModels_Added_Modified_Feb23));
        
        string IMigrationMetadata.Id
        {
            get { return "202002221930140_RxModels_Added_Modified_Feb23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
