// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Store_IssuProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Store_IssuProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202001071408441_Store_IssuProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
