// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Temp_LIS_PatientRecord_Modified_Jan15_15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Temp_LIS_PatientRecord_Modified_Jan15_15));
        
        string IMigrationMetadata.Id
        {
            get { return "202001151448595_Temp_LIS_PatientRecord_Modified_Jan15_15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
