// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Unknown_Feb13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Unknown_Feb13));
        
        string IMigrationMetadata.Id
        {
            get { return "202002130618506_Unknown_Feb13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
