// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxInitialData_Model_Modified_March_02_2020_03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxInitialData_Model_Modified_March_02_2020_03));
        
        string IMigrationMetadata.Id
        {
            get { return "202003020613369_RxInitialData_Model_Modified_March_02_2020_03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
