// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RxModel_Modified_May04_2020_0200 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RxModel_Modified_May04_2020_0200));
        
        string IMigrationMetadata.Id
        {
            get { return "202005032040537_RxModel_Modified_May04_2020_0200"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
