// <auto-generated />
namespace HDMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HpCabinCharges_HpCabinChargeSegmantDetail_Feb04 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HpCabinCharges_HpCabinChargeSegmantDetail_Feb04));
        
        string IMigrationMetadata.Id
        {
            get { return "202002041053140_HpCabinCharges_HpCabinChargeSegmantDetail_Feb04"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
